### PR TITLE
allow for interpolation to extrapolate, as needed

### PR DESCRIPTION
**Pull request by zingale**
also clean-up lagrangian_planar a little

### CODE REVIEW

**Comment by aisclark91** [comment]
by cleaning you mean to delete all the files not related to the nova problem?

**Comment by zingale** [comment]
I don't think I removed any.  I just made the write routine a function and made the output filename follow the same format as the other setups

**Review by aisclark91 — APPROVED** [review]
This solves exactly, the issue I had in mind; however, one question surges: In the process of setup this initial model in Castro: 
1. Do we need only the points below rho <10^{-5} g/cm^3 or we should include also the floor values?
2. Now the size of the layer is ~ 4.0 times 10^7 cm, so we should consider a grid of 4~5 times the size of the layer as we did before?

**Comment by aisclark91** [comment]
and yes, now I get what 'by cleaning' was. Indeed, that was a good idea.

**Comment by zingale** [comment]
as written, this will integrate the HSE model until the density hits `problem.low_density_cutoff` and then it will keep the density constant.  This is what you want.

In your simulation, you want to have a region with rho = low_density_cutoff at the top of the domain to give the model room to expand into as it heats up.  So you want to carry this integration down to that point, like we do now.

**Pull request merged**
